description: DT with description regularization

# env_defaults:
#   PYTHONPATH: $PWD:$PYTHONPATH
  
  
environment:
  image: amlt-sing/pytorch-1.8.0-cuda11.1-cudnn8-devel
  setup:
    - sudo apt-get update -y
    - sudo apt-get install -y libosmesa6-dev libgl1-mesa-glx libglfw3 libgl1-mesa-dev
    # - apt-get install libgcrypt20 libgcrypt20-dev
    - sudo apt-get update -q -y \
        && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        curl \
        git \
        libgl1-mesa-dev \
        libgl1-mesa-glx \
        libglew-dev \
        libosmesa6-dev \
        software-properties-common \
        net-tools \
        vim \
        virtualenv \
        wget \
        xpra \
        xserver-xorg-dev \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*
    - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
    - pip install azureml-mlflow tensorboard --user
    - pip install -r requirements.txt
    - export LD_LIBRARY_PATH=/usr/local/nvidia/lib64:$LD_LIBRARY_PATH
    - pip install -U tqdm
    - pip install --upgrade jinja2>=3.0

    
target:
  service: sing
  name: msrresrchvc
  # name: msrresrchlab
  workspace_name: rag-workspace-eastus

data:
  local_dir: ./data/
  remote_dir: data/

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

# list of jobs to run, we run 2 jobs in this example
jobs:
- name: rag_cpo
  sku: G1
  identity: managed
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/e033d461-1923-44a7-872b-78f1d35a86dd/resourcegroups/RAG-WUS/providers/Microsoft.ManagedIdentity/userAssignedIdentities/rag-workspace-eastus-mi"
  command:
    - export PYTHONPATH=$PWD:$PYTHONPATH; python examples/scripts/cpo.py --model_name_or_path=Qwen/Qwen2.5-3B-Instruct --per_device_train_batch_size 1 --max_steps 5000 --learning_rate 8e-6 --gradient_accumulation_steps 1 --logging_steps 10 --eval_steps 500 --output_dir="logs/qwen-3b-full-aligned-cpo" --warmup_steps 150 --report_to wandb --bf16 --logging_first_step --max_prompt_length 1024 --max_completion_length=256 --loss_type="simpo" --cpo_alpha=1.0


# search:
#   job_template:
# # you may use {random_string:s} to avoid job name collisions
# # {auto:3s} generates lr_0.00000_mom_0.5, .. etc
# # {auto:2s} generates lr_0.00000_mo_0.5, .. etc
# name: "{experiment_name:s}_{auto:3s}"
# identity: managed
# submit_args:
#   env:
#     _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/e033d461-1923-44a7-872b-78f1d35a86dd/resourcegroups/RAG-WUS/providers/Microsoft.ManagedIdentity/userAssignedIdentities/rag-workspace-eastus-mi"
# sku: 40G1
# command:
# - python experiment.py --seed 123 --env citylearn --dataset medium-expert --eta {eta} --grad_norm {grad_norm} --exp_name qt --save_path ./save/ --max_iters 20 --num_steps_per_iter 50000 --lr_decay --early_stop --k_rewards --use_discount --reprogram --desc_reg --eta3 {eta3}
#   type: hyperdrive  # hyperparameter search type: hyperdrive, random, grid.  Default: hyperdrive
#   sampling: grid  # how to explore the hyperparameter space: random, grid or bayesian. Default: bayesian
#   max_trials: 256
#   parallel_trials: 16  # number of trials to run in parallel. Default: equals to max_trials.
#   params:
# - name: eta
#   values: [0.01, 0.1, 1.0, 2.0, 4.0, 10.0, 20.0, 50.0]  # or equivalently choice(0.5, 0.9, 0.99)
# - name: grad_norm
#   # spec: hyperdrive  # the default value
#   values: [1.0, 2.0, 4.0, 10.0]
# - name: eta3
#   # spec: hyperdrive  # the default value
#   values: [0.01, 0.1, 1.0, 2.0, 4.0, 10.0, 20.0, 50.0]
  